server:
    port: 8080
spring:
    application:
        name: gateway
    security:
        oauth2:
            client:
                provider:
                    gateway:
                        issuer-uri: http://localhost:9000
                registration:
                    gateway:
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_basic
                        client-id: gateway
                        client-secret: secret
                        provider: gateway
                        redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
                        scope: openid
